from typing import Any

"""Dynamic Optimization Loader.

Closes the 'Strange Loop' of self-improvement by allowing the system
to dynamically load and apply optimizations generated by agents.

Safety:
- Validates signatures
- Sandboxes execution (basic)
- Requires 'register' entry point

Note: Consolidated from kagami.core.optimizations.loader
"""

import importlib
import logging
import pkgutil
import sys

from fastapi import FastAPI

logger = logging.getLogger(__name__)


class DynamicOptimizationLoader:
    """Loads agent-generated optimizations from a Python package path."""

    def __init__(self, package_path: str = "kagami.core.training.optimization"):
        self.package_path = package_path
        self._loaded_modules: dict[str, Any] = {}

    def load_and_apply(self, app: FastAPI) -> int:
        """Scan, load, and apply optimizations.

        Returns:
            Count of successfully applied optimizations.
        """
        count = 0

        # Ensure package exists
        try:
            package = importlib.import_module(self.package_path)
        except ImportError:
            logger.info(f"Optimization package {self.package_path} not found, skipping.")
            return 0

        if not hasattr(package, "__path__"):
            return 0

        # Keep startup logs clean: only emit INFO when we actually apply something.
        logger.debug("Scanning for dynamic optimizations in %s", self.package_path)

        for _, name, _is_pkg in pkgutil.iter_modules(package.__path__):
            if name.startswith("_") or name in ("dynamic_loader", "loader"):
                continue

            full_name = f"{self.package_path}.{name}"

            try:
                if full_name in sys.modules:
                    module = importlib.reload(sys.modules[full_name])
                else:
                    module = importlib.import_module(full_name)

                # Look for registration hook
                if hasattr(module, "register"):
                    logger.info(f"✨ Applying optimization: {name}")
                    try:
                        module.register(app)
                        self._loaded_modules[name] = module
                        count += 1
                    except Exception as e:
                        logger.error(f"❌ Failed to apply optimization {name}: {e}")
                elif hasattr(module, "Optimization"):
                    # Class-based pattern
                    logger.info(f"✨ Applying optimization class: {name}")
                    try:
                        opt = module.Optimization()
                        opt.apply(app)
                        self._loaded_modules[name] = module
                        count += 1
                    except Exception as e:
                        logger.error(f"❌ Failed to apply optimization class {name}: {e}")
                else:
                    logger.debug(f"Skipping {name} (no register() or Optimization class)")

            except Exception as e:
                logger.error(f"❌ Failed to load module {name}: {e}")

        if count > 0:
            logger.info(f"✅ Applied {count} dynamic optimizations")

        return count


_loader = DynamicOptimizationLoader()


def load_dynamic_optimizations(app: FastAPI) -> int:
    """Public entry point."""
    return _loader.load_and_apply(app)


__all__ = ["DynamicOptimizationLoader", "load_dynamic_optimizations"]
