"""Safety System Metrics.

Centralized metrics for CBF, honesty validator, memory guard, and threat instinct.
"""

from .core import Counter, Gauge, Histogram

# Control Barrier Function
CBF_EVALUATIONS_TOTAL = Counter(
    "kagami_cbf_evaluations_total",
    "Total CBF evaluations",
    ["result"],
)

CBF_BLOCKS_TOTAL = Counter(
    "kagami_cbf_blocks_total",
    "Operations blocked by CBF",
    ["operation", "reason"],
)

CBF_BARRIER_VALUE = Histogram(
    "kagami_cbf_barrier_value",
    "CBF barrier function values",
    ["operation"],
)

CBF_AGENT_SAFETY_DURATION_SECONDS = Histogram(
    "kagami_cbf_agent_safety_duration_seconds",
    "Time spent in CBF safety checks",
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
)

CBF_CONTROL_SIGNAL = Histogram(
    "kagami_cbf_control_signal",
    "Control signals generated by CBF",
    ["component"],  # aggression, speed
    buckets=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

CBF_STATE_RISK = Gauge(
    "kagami_cbf_state_risk",
    "Current risk level of safety state components",
    ["component"],  # threat, uncertainty, complexity, predictive_risk
)

# NEW: CBF h(x) barrier value for real-time safety monitoring
CBF_BARRIER_VALUE_CURRENT = Gauge(
    "kagami_cbf_barrier_value_current",
    "Current CBF barrier function h(x) value - positive is safe, negative is unsafe",
)

# NEW: CBF constraint activity (when QP solver is actively adjusting control)
CBF_CONSTRAINT_ACTIVE = Gauge(
    "kagami_cbf_constraint_active",
    "Whether CBF constraint is currently active (1) or not (0)",
)

# NEW: CBF context validation failures for security monitoring
CBF_CONTEXT_VALIDATION_FAILURES_TOTAL = Counter(
    "kagami_cbf_context_validation_failures_total",
    "Context validation failures detected by CBF security checks",
    ["reason"],  # out_of_range, operation_mismatch, target_mismatch
)

# NEW: CBF adaptive learning metrics
CBF_ALPHA_VALUE = Gauge(
    "kagami_cbf_alpha_value",
    "Current class-K function alpha parameter value",
)

CBF_SAFETY_MARGIN = Histogram(
    "kagami_cbf_safety_margin",
    "Safety margin from barrier boundary (h(x) - 0)",
    buckets=[-0.5, -0.3, -0.1, 0.0, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0],
)

# Honesty Validator
HONESTY_VALIDATIONS_TOTAL = Counter(
    "kagami_honesty_validations_total",
    "Total honesty validations",
    ["result"],
)

HONESTY_VIOLATIONS_TOTAL = Counter(
    "kagami_honesty_violations_total",
    "Honesty violations detected",
    ["evidence_type"],
)

# Memory Guard
AGENT_MEMORY_BYTES = Gauge(
    "kagami_agent_memory_bytes",
    "Agent memory usage in bytes",
    ["agent_name"],
)

AGENT_MEMORY_PRESSURE = Histogram(
    "kagami_agent_memory_pressure",
    "Agent memory pressure (0-1)",
    ["agent_name"],
)

AGENT_MEMORY_VIOLATIONS = Counter(
    "kagami_agent_memory_violations_total",
    "Memory limit violations",
    ["agent_name", "violation_type"],
)

AGENT_MEMORY_BUDGET_GB = Gauge(
    "kagami_agent_memory_budget_gb",
    "Agent memory budget in GB",
    ["agent_name"],
)

# Threat Instinct
THREAT_ASSESSMENTS_TOTAL = Counter(
    "kagami_threat_assessments_total",
    "Total threat assessments",
    ["result"],
)

THREAT_INSTINCT_BLOCKS_TOTAL = Counter(
    "kagami_threat_instinct_blocks_total",
    "Tasks blocked by threat instinct",
    ["domain", "threat_level"],
)

THREAT_INSTINCT_FAILURES_TOTAL = Counter(
    "kagami_threat_instinct_failures_total",
    "Threat instinct system failures",
    ["reason"],
)

# Meta-level Instinct Critiques
META_CRITIQUES_TOTAL = Counter(
    "kagami_meta_critiques_total",
    "Meta-level instinct critiques",
    ["critique_type"],
)

SAFETY_INSTINCT_BLOCKS_TOTAL = Counter(
    "kagami_safety_instinct_blocks_total",
    "Tasks blocked by safety instinct",
    ["instinct_type", "reason"],
)

KAGAMI_SAFETY_VIOLATIONS_TOTAL = Counter(
    "kagami_safety_violations_total",
    "Total safety violations recorded across guardrails",
    ["system"],
)

__all__ = [
    "AGENT_MEMORY_BUDGET_GB",
    "AGENT_MEMORY_BYTES",
    "AGENT_MEMORY_PRESSURE",
    "AGENT_MEMORY_VIOLATIONS",
    "CBF_AGENT_SAFETY_DURATION_SECONDS",
    "CBF_ALPHA_VALUE",
    "CBF_BARRIER_VALUE",
    "CBF_BARRIER_VALUE_CURRENT",
    "CBF_BLOCKS_TOTAL",
    "CBF_CONSTRAINT_ACTIVE",
    "CBF_CONTEXT_VALIDATION_FAILURES_TOTAL",
    "CBF_CONTROL_SIGNAL",
    "CBF_EVALUATIONS_TOTAL",
    "CBF_SAFETY_MARGIN",
    "CBF_STATE_RISK",
    "HONESTY_VALIDATIONS_TOTAL",
    "HONESTY_VIOLATIONS_TOTAL",
    "KAGAMI_SAFETY_VIOLATIONS_TOTAL",
    "META_CRITIQUES_TOTAL",
    "SAFETY_INSTINCT_BLOCKS_TOTAL",
    "THREAT_ASSESSMENTS_TOTAL",
    "THREAT_INSTINCT_BLOCKS_TOTAL",
    "THREAT_INSTINCT_FAILURES_TOTAL",
]
