"""Unified Shot — Single source of truth for production units.

A Shot is the atomic unit of video production. It represents one continuous
piece of footage, whether generated by:
- Runway (action, establishing, cutaway)
- HeyGen (dialogue with lip sync)
- Static image with Ken Burns effect
- Screen recording
- Camera capture

This replaces:
- effectors/video/hybrid_composer.py Shot, ShotType
- kagami_media/production/shot.py Shot, ShotResult, ShotRenderer
- core/media/production/scene.py Beat (similar concept)
"""

from __future__ import annotations

import asyncio
import logging
import subprocess
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path("/tmp/kagami_shots")


class ShotType(str, Enum):
    """Type of shot — determines which generator to use.

    Based on TED Talk cinematography and Roger Deakins principles:
    - Multi-camera coverage (wide, medium, close)
    - Purposeful movement serves narrative
    - Balanced composition with environmental context
    """

    # === Front/Speaker shots (TED Talk standard) ===
    FRONT_WIDE = "front_wide"  # Full stage, speaker + backdrop + slides
    FRONT_MEDIUM = "front_medium"  # Waist up, gestures visible
    FRONT_CLOSEUP = "front_closeup"  # Face only, emotions + nuance
    FRONT_EXTREME_CLOSEUP = "front_xcu"  # Eyes/detail for emphasis

    # === HeyGen shots (requires face, lip sync) ===
    DIALOGUE = "dialogue"  # Character speaking (default front medium)
    MONOLOGUE = "monologue"  # Extended speaking

    # === Audience/Reverse shots (back of speaker, crowd views) ===
    AUDIENCE = "audience"  # View OF the audience (wide)
    AUDIENCE_CLOSEUP = "audience_closeup"  # Single audience member reacting
    REVERSE = "reverse"  # Back of speaker's head, facing audience
    OVER_SHOULDER_AUDIENCE = "ots_audience"  # Over speaker's shoulder to crowd
    POV_AUDIENCE = "pov_audience"  # From audience perspective at speaker
    REACTION_AUDIENCE = "reaction_audience"  # Audience reacting

    # === Two-shots and coverage ===
    TWO_SHOT = "two_shot"  # Speaker + interviewer/moderator
    WALKING = "walking"  # Speaker walking/pacing (Deakins tracking)
    PROFILE = "profile"  # Side view of speaker

    # === Runway shots (any subject, no lip sync) ===
    ACTION = "action"  # Subject in motion
    REACTION = "reaction"  # Subject reacting
    ESTABLISHING = "establishing"  # Scene-setting wide (venue exterior)
    CUTAWAY = "cutaway"  # B-roll, detail (hands, notes, screen)
    TRANSITION = "transition"  # Crossfade/wipe

    # === Static/simple shots ===
    STILL = "still"  # Static image
    TITLE = "title"  # Text on screen
    LOWER_THIRD = "lower_third"  # Name/title card
    SLIDES = "slides"  # Full-screen presentation slides


class CameraAngle(str, Enum):
    """Camera framing — Roger Deakins inspired.

    Principles:
    - Wider lenses (32mm, 40mm) for environmental context
    - Balanced, geometric composition
    - Movement only when narrative requires it
    """

    # === Standard framing (TED Talk coverage) ===
    EXTREME_WIDE = "extreme_wide"  # Full venue/stage
    WIDE = "wide"  # Full speaker + context
    MEDIUM_WIDE = "medium_wide"  # Knees up
    MEDIUM = "medium"  # Waist up (most common)
    MEDIUM_CLOSE = "medium_close"  # Chest up
    CLOSE = "close"  # Head and shoulders
    EXTREME_CLOSE = "extreme_close"  # Face detail

    # === Angle variations ===
    FRONT = "front"  # Direct front (0°)
    THREE_QUARTER_FRONT = "three_quarter_front"  # 45° from front
    PROFILE = "profile"  # Side view (90°)
    THREE_QUARTER_BACK = "three_quarter_back"  # 135° (see some face)
    BEHIND = "behind"  # Full back view (180°)

    # === Special angles ===
    OVER_SHOULDER = "over_shoulder"  # OTS standard
    POV = "pov"  # Point of view
    HIGH_ANGLE = "high_angle"  # Looking down (vulnerability)
    LOW_ANGLE = "low_angle"  # Looking up (power)
    DUTCH = "dutch"  # Tilted (tension)
    CROWD_WIDE = "crowd_wide"  # Wide shot of audience
    BIRDS_EYE = "birds_eye"  # Directly overhead

    # === Movement ===
    TRACKING = "tracking"  # Following subject movement
    DOLLY = "dolly"  # Push in/pull out
    CRANE = "crane"  # Vertical movement


@dataclass
class Shot:
    """Universal production unit.

    Attributes:
        type: Shot type (determines generator)

        # Content (provide one)
        text: Dialogue text (for DIALOGUE/MONOLOGUE)
        action_prompt: Motion description (for ACTION/REACTION/ESTABLISHING)

        # Subject
        character: Character identity_id (loads from metadata.json)
        subject_image: Path to image (for non-character subjects)

        # Audio
        sfx: Sound effect names
        music: Background music cue
        ambient: Ambient sound

        # Framing
        camera: Camera angle
        duration_s: Target duration
        motion: Emotional direction

        # Voice (ElevenLabs)
        voice_remix: Voice remix description (e.g., "warmer British accent")
        voice_remix_strength: How much to modify voice (0.1-1.0)
        voice_id: Optional specific voice_id to use (for remixed variants)

        # Effects
        color_grade: Color grading preset
        vignette: Vignette strength (0-1)
        grain: Film grain amount (0-1)
    """

    # Shot type
    type: ShotType = ShotType.DIALOGUE

    # Content (at least one required)
    text: str | None = None
    action_prompt: str | None = None

    # Subject
    character: str | None = None
    subject_image: Path | None = None

    # Audio layers
    sfx: list[str] = field(default_factory=list)
    music: str | None = None
    ambient: str | None = None

    # Framing
    camera: CameraAngle = CameraAngle.MEDIUM
    duration_s: float = 5.0
    motion: str = "natural"

    # Voice (ElevenLabs remixing)
    voice_remix: str | None = None  # e.g., "warmer British accent"
    voice_remix_strength: float = 0.5  # 0.1-1.0
    voice_id: str | None = None  # Override voice_id for pre-remixed variants

    # Effects
    color_grade: str | None = None
    vignette: float = 0.0
    grain: float = 0.0

    # Metadata
    id: str | None = None

    def __post_init__(self):
        """Validate shot configuration."""
        if self.type in (ShotType.DIALOGUE, ShotType.MONOLOGUE):
            if not self.text:
                raise ValueError(f"{self.type.value} shot requires text")
            if not self.character and not self.subject_image:
                raise ValueError(f"{self.type.value} shot requires character or subject_image")

        elif self.type in (
            ShotType.ACTION,
            ShotType.REACTION,
            ShotType.ESTABLISHING,
            ShotType.CUTAWAY,
        ):
            if not self.action_prompt:
                raise ValueError(f"{self.type.value} shot requires action_prompt")

    @property
    def needs_runway(self) -> bool:
        """Whether this shot should use Runway (motion video)."""
        return self.type in (
            # Action/B-roll
            ShotType.ACTION,
            ShotType.REACTION,
            ShotType.ESTABLISHING,
            ShotType.CUTAWAY,
            ShotType.WALKING,
            # Audience shots
            ShotType.AUDIENCE,
            ShotType.AUDIENCE_CLOSEUP,
            ShotType.REVERSE,
            ShotType.OVER_SHOULDER_AUDIENCE,
            ShotType.POV_AUDIENCE,
            ShotType.REACTION_AUDIENCE,
        )

    @property
    def needs_heygen(self) -> bool:
        """Whether this shot should use HeyGen (lip sync)."""
        return self.type in (ShotType.DIALOGUE, ShotType.MONOLOGUE)

    @property
    def needs_tts(self) -> bool:
        """Whether this shot needs TTS audio."""
        return self.text is not None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "type": self.type.value,
            "text": self.text,
            "action_prompt": self.action_prompt,
            "character": self.character,
            "subject_image": str(self.subject_image) if self.subject_image else None,
            "sfx": self.sfx,
            "music": self.music,
            "ambient": self.ambient,
            "camera": self.camera.value,
            "duration_s": self.duration_s,
            "motion": self.motion,
            "voice_remix": self.voice_remix,
            "voice_remix_strength": self.voice_remix_strength,
            "voice_id": self.voice_id,
            "color_grade": self.color_grade,
            "vignette": self.vignette,
            "grain": self.grain,
            "id": self.id,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Shot:
        """Deserialize from dictionary."""
        return cls(
            type=ShotType(data.get("type", "dialogue")),
            text=data.get("text"),
            action_prompt=data.get("action_prompt"),
            character=data.get("character"),
            subject_image=Path(data["subject_image"]) if data.get("subject_image") else None,
            sfx=data.get("sfx", []),
            music=data.get("music"),
            ambient=data.get("ambient"),
            camera=CameraAngle(data.get("camera", "medium")),
            duration_s=data.get("duration_s", 5.0),
            motion=data.get("motion", "natural"),
            voice_remix=data.get("voice_remix"),
            voice_remix_strength=data.get("voice_remix_strength", 0.5),
            voice_id=data.get("voice_id"),
            color_grade=data.get("color_grade"),
            vignette=data.get("vignette", 0.0),
            grain=data.get("grain", 0.0),
            id=data.get("id"),
        )


@dataclass
class ShotResult:
    """Result of rendering a shot."""

    success: bool
    video_path: Path | None = None
    audio_path: Path | None = None
    duration_s: float = 0.0
    render_time_s: float = 0.0
    shot: Shot | None = None
    error: str | None = None

    # Generation metadata
    generator_used: str = ""  # runway, heygen, static, etc.
    cost_cents: float = 0.0


# =============================================================================
# RENDERING
# =============================================================================


class ShotRenderer:
    """Renders shots using appropriate generators.

    Automatically routes to:
    - Runway: ACTION, REACTION, ESTABLISHING, CUTAWAY
    - HeyGen: DIALOGUE, MONOLOGUE
    - Static: STILL, TITLE, LOWER_THIRD

    Audio is rendered via AudioRenderer with:
    - Voice (TTS)
    - SFX
    - Music
    - Ambient
    """

    def __init__(self):
        self._runway = None
        self._heygen = None
        self._tts = None
        self._audio_renderer = None
        self._initialized = False

    async def initialize(self) -> None:
        """Initialize generators."""
        if self._initialized:
            return

        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

        # Initialize audio renderer
        from kagami_studio.composition.audio import get_audio_renderer

        self._audio_renderer = await get_audio_renderer()

        self._initialized = True
        logger.info("ShotRenderer initialized")

    async def render(self, shot: Shot) -> ShotResult:
        """Render a shot.

        Rendering flow:
        1. Generate video (HeyGen/Runway/Static)
        2. Generate voice audio (TTS)
        3. Mix audio tracks (voice + sfx + music + ambient)
        4. Combine video + audio

        Args:
            shot: Shot definition

        Returns:
            ShotResult with video/audio paths
        """
        if not self._initialized:
            await self.initialize()

        start = time.perf_counter()

        try:
            # Route to appropriate generator
            if shot.needs_heygen:
                result = await self._render_heygen(shot)
            elif shot.needs_runway:
                result = await self._render_runway(shot)
            else:
                result = await self._render_static(shot)

            # If we have additional audio layers, mix them
            if result.success and result.audio_path and (shot.sfx or shot.music or shot.ambient):
                result = await self._mix_shot_audio(shot, result)

            result.render_time_s = time.perf_counter() - start
            return result

        except Exception as e:
            logger.error(f"Shot render failed: {e}")
            return ShotResult(
                success=False,
                error=str(e),
                shot=shot,
                render_time_s=time.perf_counter() - start,
            )

    async def _mix_shot_audio(self, shot: Shot, result: ShotResult) -> ShotResult:
        """Mix additional audio tracks for a shot.

        Uses AudioRenderer to mix:
        - Voice (from TTS)
        - SFX (sound effects)
        - Music (background)
        - Ambient (environmental)
        """
        if not self._audio_renderer:
            return result

        # Resolve SFX paths (would load from asset library)
        sfx_paths = []
        for sfx_name in shot.sfx:
            sfx_path = self._resolve_sfx_path(sfx_name)
            if sfx_path:
                sfx_paths.append(sfx_path)

        # Resolve music/ambient paths
        music_path = self._resolve_music_path(shot.music) if shot.music else None
        ambient_path = self._resolve_ambient_path(shot.ambient) if shot.ambient else None

        # Mix audio
        audio_result = await self._audio_renderer.render_shot_audio(
            voice_path=result.audio_path,
            sfx_paths=sfx_paths if sfx_paths else None,
            music_path=music_path,
            ambient_path=ambient_path,
        )

        if audio_result.success and audio_result.audio_path:
            # Replace audio in video if we have video
            if result.video_path:
                final_video = await self._audio_renderer.combine_video_audio(
                    result.video_path,
                    audio_result.audio_path,
                )
                if final_video:
                    result.video_path = final_video

            result.audio_path = audio_result.audio_path

        return result

    def _resolve_sfx_path(self, sfx_name: str) -> Path | None:
        """Resolve SFX name to file path."""
        # Check common locations
        sfx_dirs = [
            Path("assets/audio/sfx"),
            Path("assets/sfx"),
            Path("/tmp/kagami_sfx"),
        ]

        for sfx_dir in sfx_dirs:
            for ext in [".mp3", ".wav", ".ogg"]:
                path = sfx_dir / f"{sfx_name}{ext}"
                if path.exists():
                    return path

        return None

    def _resolve_music_path(self, music_name: str) -> Path | None:
        """Resolve music name to file path."""
        music_dirs = [
            Path("assets/audio/music"),
            Path("assets/music"),
            Path("/tmp/kagami_music"),
        ]

        for music_dir in music_dirs:
            for ext in [".mp3", ".wav", ".ogg"]:
                path = music_dir / f"{music_name}{ext}"
                if path.exists():
                    return path

        return None

    def _resolve_ambient_path(self, ambient_name: str) -> Path | None:
        """Resolve ambient name to file path."""
        ambient_dirs = [
            Path("assets/audio/ambient"),
            Path("assets/ambient"),
            Path("/tmp/kagami_ambient"),
        ]

        for ambient_dir in ambient_dirs:
            for ext in [".mp3", ".wav", ".ogg"]:
                path = ambient_dir / f"{ambient_name}{ext}"
                if path.exists():
                    return path

        return None

    async def _render_heygen(self, shot: Shot) -> ShotResult:
        """Render dialogue shot with HeyGen Avatar IV."""
        import httpx
        from kagami.core.security import get_secret

        from kagami_studio.characters import load_character

        heygen_key = get_secret("heygen_api_key")
        if not heygen_key:
            return ShotResult(success=False, error="HeyGen API key not found", shot=shot)

        # Get character
        char = None
        image_path = shot.subject_image

        if shot.character:
            char = load_character(shot.character)
            if char and char.avatar.primary_image:
                image_path = char.avatar.primary_image

        if not image_path or not image_path.exists():
            return ShotResult(success=False, error="No image for HeyGen", shot=shot)

        # Generate TTS first
        audio_result = await self._generate_tts(shot)
        if not audio_result.success:
            return ShotResult(success=False, error=f"TTS failed: {audio_result.error}", shot=shot)

        async with httpx.AsyncClient(timeout=120.0) as client:
            # Upload image
            resp = await client.post(
                "https://upload.heygen.com/v1/asset",
                headers={"X-API-KEY": heygen_key, "Content-Type": "image/png"},
                content=image_path.read_bytes(),
            )
            if resp.status_code != 200:
                return ShotResult(
                    success=False, error=f"Image upload failed: {resp.text[:200]}", shot=shot
                )

            image_key = resp.json().get("data", {}).get("image_key")

            # Upload audio
            resp = await client.post(
                "https://upload.heygen.com/v1/asset",
                headers={"X-API-KEY": heygen_key, "Content-Type": "audio/mpeg"},
                content=audio_result.audio_path.read_bytes(),
            )
            if resp.status_code != 200:
                return ShotResult(
                    success=False, error=f"Audio upload failed: {resp.text[:200]}", shot=shot
                )

            audio_url = resp.json().get("data", {}).get("url")

            # Submit Avatar IV job
            payload = {
                "image_key": image_key,
                "video_title": f"shot_{int(time.time())}",
                "video_orientation": "landscape",
                "fit": "contain",
                "audio_url": audio_url,
                "custom_motion_prompt": f"{shot.motion} expression, {shot.camera.value} framing",
                "enhance_custom_motion_prompt": True,
            }

            resp = await client.post(
                "https://api.heygen.com/v2/video/av4/generate",
                headers={"X-Api-Key": heygen_key, "Content-Type": "application/json"},
                json=payload,
            )

            if resp.status_code != 200:
                return ShotResult(
                    success=False, error=f"HeyGen submit failed: {resp.text[:200]}", shot=shot
                )

            video_id = resp.json().get("data", {}).get("video_id")

            # Poll for completion
            video_url = None
            for _ in range(120):  # 10 minute timeout
                resp = await client.get(
                    f"https://api.heygen.com/v1/video_status.get?video_id={video_id}",
                    headers={"X-Api-Key": heygen_key},
                )
                data = resp.json().get("data", {})
                status = data.get("status")

                if status == "completed":
                    video_url = data.get("video_url")
                    break
                elif status == "failed":
                    return ShotResult(
                        success=False, error=f"HeyGen failed: {data.get('error')}", shot=shot
                    )

                await asyncio.sleep(5)

            if not video_url:
                return ShotResult(success=False, error="HeyGen timeout", shot=shot)

            # Download video
            resp = await client.get(video_url)
            video_path = OUTPUT_DIR / f"heygen_{video_id}.mp4"
            video_path.write_bytes(resp.content)

            # Get duration
            duration = self._get_video_duration(video_path)

            return ShotResult(
                success=True,
                video_path=video_path,
                audio_path=audio_result.audio_path,
                duration_s=duration,
                shot=shot,
                generator_used="heygen",
            )

    async def _render_runway(self, shot: Shot) -> ShotResult:
        """Render action shot with Runway Gen-3/4."""
        # For now, return placeholder - Runway API integration
        # would go here when available
        logger.warning("Runway rendering not yet implemented")
        return ShotResult(
            success=False,
            error="Runway rendering not implemented",
            shot=shot,
            generator_used="runway",
        )

    async def _render_static(self, shot: Shot) -> ShotResult:
        """Render static/title shot."""
        # Simple static shot - Ken Burns on image
        if shot.subject_image and shot.subject_image.exists():
            video_path = OUTPUT_DIR / f"static_{int(time.time() * 1000)}.mp4"

            # Ken Burns zoom effect
            subprocess.run(
                [
                    "ffmpeg",
                    "-y",
                    "-loop",
                    "1",
                    "-i",
                    str(shot.subject_image),
                    "-vf",
                    "zoompan=z='min(zoom+0.001,1.5)':d=1:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s=1920x1080",
                    "-t",
                    str(shot.duration_s),
                    "-c:v",
                    "libx264",
                    "-pix_fmt",
                    "yuv420p",
                    str(video_path),
                ],
                capture_output=True,
                check=True,
            )

            return ShotResult(
                success=True,
                video_path=video_path,
                duration_s=shot.duration_s,
                shot=shot,
                generator_used="static",
            )

        return ShotResult(success=False, error="No image for static shot", shot=shot)

    async def _generate_tts(self, shot: Shot) -> SpeakResult:
        """Generate TTS audio for a shot.

        Supports:
        - Standard character voice
        - Voice remixing via shot.voice_remix
        - Pre-remixed voice variants via shot.voice_id
        """
        from kagami_studio.characters.voice import SpeakResult, get_voice, speak

        if not shot.text:
            return SpeakResult(success=False, error="No text for TTS")

        character = shot.character or "kagami"

        # If shot has a remix description, create remixed voice on-the-fly
        if shot.voice_remix:
            try:
                voice = await get_voice(character)
                # Preview and use first result (for production, use create_remix_variant for permanent)
                from kagami.core.services.voice.remixing import get_voice_remixer

                remixer = await get_voice_remixer()
                previews = await remixer.preview_remix(
                    voice_id=voice._character.voice.voice_id if voice._character else "",
                    description=shot.voice_remix,
                    prompt_strength=shot.voice_remix_strength,
                    script=shot.text,  # Use actual text for better preview
                    num_previews=1,
                )
                if previews and previews[0].preview_path:
                    logger.info(f"🎤 Using remixed voice: {shot.voice_remix}")
                    return SpeakResult(
                        success=True,
                        audio_path=previews[0].preview_path,
                        audio_bytes=previews[0].audio_data,
                        character=character,
                        mood=shot.motion,
                        text=shot.text,
                    )
            except Exception as e:
                logger.warning(f"Voice remix failed, falling back to standard: {e}")

        # If shot has a specific voice_id (pre-remixed variant), use it directly
        if shot.voice_id:
            try:
                import tempfile
                import time as time_module

                from elevenlabs import ElevenLabs
                from kagami.core.security import get_secret

                api_key = get_secret("elevenlabs_api_key")
                client = ElevenLabs(api_key=api_key)

                chunks = []
                audio_stream = client.text_to_speech.stream(
                    voice_id=shot.voice_id,
                    text=shot.text,
                    model_id="eleven_v3",  # ALWAYS V3 for audio tags
                )
                for chunk in audio_stream:
                    if isinstance(chunk, bytes):
                        chunks.append(chunk)

                audio_bytes = b"".join(chunks)
                temp_dir = Path(tempfile.gettempdir()) / "kagami_shot_voices"
                temp_dir.mkdir(exist_ok=True)
                audio_path = temp_dir / f"shot_{int(time_module.time() * 1000)}.mp3"
                audio_path.write_bytes(audio_bytes)

                logger.info(f"🎤 Using custom voice_id: {shot.voice_id[:8]}...")
                return SpeakResult(
                    success=True,
                    audio_path=audio_path,
                    audio_bytes=audio_bytes,
                    character=character,
                    mood=shot.motion,
                    text=shot.text,
                )
            except Exception as e:
                logger.warning(f"Custom voice_id failed, falling back: {e}")

        # Standard path: use character's default voice
        return await speak(character, shot.text, mood=shot.motion)

    @staticmethod
    def _get_video_duration(path: Path) -> float:
        """Get video duration in seconds."""
        result = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-show_entries",
                "format=duration",
                "-of",
                "csv=p=0",
                str(path),
            ],
            capture_output=True,
            text=True,
        )
        return float(result.stdout.strip()) if result.stdout.strip() else 0.0


# Convenience function
_renderer: ShotRenderer | None = None


async def render_shot(shot: Shot) -> ShotResult:
    """Render a single shot (convenience function)."""
    global _renderer

    if _renderer is None:
        _renderer = ShotRenderer()
        await _renderer.initialize()

    return await _renderer.render(shot)


# Import SpeakResult for type hints
from kagami_studio.characters.voice import SpeakResult

__all__ = [
    "CameraAngle",
    "Shot",
    "ShotRenderer",
    "ShotResult",
    "ShotType",
    "render_shot",
]
