"""Wellness Monitoring Service.

Supports aging-in-place and elder care with:
- Activity pattern monitoring (non-invasive)
- Fall detection integration
- Medication reminder scheduling
- Anomaly detection (unusual inactivity)
- Family alerts and check-ins

Created: December 31, 2025 (Diverse Personas)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


class AlertLevel(str, Enum):
    INFO = "info"
    CONCERN = "concern"
    URGENT = "urgent"
    EMERGENCY = "emergency"


@dataclass
class ActivityPattern:
    """Tracks normal activity patterns for a user."""

    user_id: str
    typical_wake_time: str = "07:00"
    typical_sleep_time: str = "22:00"
    typical_active_rooms: list[str] = field(default_factory=list)
    typical_bathroom_visits_per_night: int = 2
    last_motion_detected: datetime | None = None
    last_activity_summary: str = ""


@dataclass
class WellnessAlert:
    """An alert generated by the wellness system."""

    id: str
    user_id: str
    level: AlertLevel
    category: str  # "inactivity", "fall", "medication", "anomaly"
    message: str
    created_at: datetime
    acknowledged_at: datetime | None = None
    acknowledged_by: str | None = None
    escalated_to: list[str] = field(default_factory=list)


@dataclass
class MedicationReminder:
    """A scheduled medication reminder."""

    id: str
    user_id: str
    medication_name: str
    scheduled_time: str  # "08:00"
    days: list[int] = field(default_factory=lambda: [0, 1, 2, 3, 4, 5, 6])  # All days
    notification_method: str = "voice"  # "voice", "visual", "both"
    confirmation_required: bool = True
    snooze_limit: int = 2
    caregiver_alert_after_minutes: int = 30


class WellnessService:
    """Service for wellness monitoring and elder support."""

    def __init__(self) -> None:
        self._activity_patterns: dict[str, ActivityPattern] = {}
        self._alerts: list[WellnessAlert] = []
        self._medication_reminders: dict[str, list[MedicationReminder]] = {}
        self._initialized = False

    async def initialize(self) -> None:
        """Initialize the wellness service."""
        if self._initialized:
            return
        logger.info("Wellness service initialized")
        self._initialized = True

    async def register_user(
        self,
        user_id: str,
        typical_wake_time: str = "07:00",
        typical_sleep_time: str = "22:00",
        active_rooms: list[str] | None = None,
    ) -> ActivityPattern:
        """Register a user for wellness monitoring."""
        pattern = ActivityPattern(
            user_id=user_id,
            typical_wake_time=typical_wake_time,
            typical_sleep_time=typical_sleep_time,
            typical_active_rooms=active_rooms or [],
        )
        self._activity_patterns[user_id] = pattern
        logger.info(f"Registered user {user_id} for wellness monitoring")
        return pattern

    async def record_motion(self, user_id: str, room: str) -> None:
        """Record motion detected for a user."""
        if user_id in self._activity_patterns:
            self._activity_patterns[user_id].last_motion_detected = datetime.now()
            logger.debug(f"Motion recorded for {user_id} in {room}")

    async def check_inactivity(
        self,
        user_id: str,
        threshold_minutes: int = 120,
    ) -> WellnessAlert | None:
        """Check if user has been inactive too long."""
        pattern = self._activity_patterns.get(user_id)
        if not pattern or not pattern.last_motion_detected:
            return None

        inactive_duration = datetime.now() - pattern.last_motion_detected
        if inactive_duration > timedelta(minutes=threshold_minutes):
            alert = WellnessAlert(
                id=f"inactivity-{user_id}-{datetime.now().isoformat()}",
                user_id=user_id,
                level=AlertLevel.CONCERN,
                category="inactivity",
                message=f"No activity detected for {int(inactive_duration.total_seconds() / 60)} minutes",
                created_at=datetime.now(),
            )
            self._alerts.append(alert)
            return alert
        return None

    async def add_medication_reminder(
        self,
        user_id: str,
        medication_name: str,
        scheduled_time: str,
        days: list[int] | None = None,
        notification_method: str = "voice",
    ) -> MedicationReminder:
        """Add a medication reminder for a user."""
        reminder = MedicationReminder(
            id=f"med-{user_id}-{medication_name}",
            user_id=user_id,
            medication_name=medication_name,
            scheduled_time=scheduled_time,
            days=days or [0, 1, 2, 3, 4, 5, 6],
            notification_method=notification_method,
        )
        if user_id not in self._medication_reminders:
            self._medication_reminders[user_id] = []
        self._medication_reminders[user_id].append(reminder)
        return reminder

    async def get_daily_summary(self, user_id: str) -> dict[str, Any]:
        """Get daily wellness summary for family dashboard."""
        pattern = self._activity_patterns.get(user_id)
        return {
            "user_id": user_id,
            "last_activity": pattern.last_motion_detected.isoformat()
            if pattern and pattern.last_motion_detected
            else None,
            "alerts_today": len(
                [
                    a
                    for a in self._alerts
                    if a.user_id == user_id and a.created_at.date() == datetime.now().date()
                ]
            ),
            "medications_due": len(self._medication_reminders.get(user_id, [])),
            "status": "normal",
        }

    async def initiate_check_in(self, user_id: str, initiated_by: str = "family") -> dict[str, Any]:
        """Initiate a wellness check-in."""
        logger.info(f"Wellness check-in initiated for {user_id} by {initiated_by}")
        return {
            "user_id": user_id,
            "initiated_by": initiated_by,
            "initiated_at": datetime.now().isoformat(),
            "status": "pending",
        }


# Singleton instance
_wellness_service: WellnessService | None = None


async def get_wellness_service() -> WellnessService:
    """Get the wellness service singleton."""
    global _wellness_service
    if _wellness_service is None:
        _wellness_service = WellnessService()
        await _wellness_service.initialize()
    return _wellness_service


__all__ = [
    "ActivityPattern",
    "AlertLevel",
    "MedicationReminder",
    "WellnessAlert",
    "WellnessService",
    "get_wellness_service",
]
