name: kagami-mps
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.*
  - pytorch=2.5.*
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - accelerate=0.31.*
  - tokenizers>=0.20,<0.21
  - transformers=4.46.2
  - sentence-transformers=3.0.1
  - sentencepiece
  - huggingface_hub
  - requests
  - redis-py
  - uvicorn
  - fastapi
  - pydantic
  - pip:
      - openai>=1.40.0
      - tf-keras
      - websockets>=11.0.3
      - outlines>=0.0.37
      - -r requirements.txt
