"""Crystal Testing Module — Test Generation Infrastructure.

Provides test generation and property-based testing:
- Unit test generation from function signatures
- Property-based test generation (Hypothesis-style)
- Edge case enumeration
- Coverage-guided test generation

Created: December 28, 2025
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any, get_type_hints

logger = logging.getLogger(__name__)


@dataclass
class TestCase:
    """A single test case."""

    name: str
    inputs: dict[str, Any]
    expected: Any | None = None
    description: str = ""
    is_edge_case: bool = False


@dataclass
class TestSuite:
    """A collection of test cases."""

    name: str
    test_cases: list[TestCase] = field(default_factory=list[Any])
    function_name: str = ""
    coverage_hints: list[str] = field(default_factory=list[Any])

    def to_pytest(self) -> str:
        """Generate pytest code for this test suite."""
        lines = [
            "import pytest",
            "",
            f"# Test suite for {self.function_name}",
            "# Generated by Crystal verification module",
            "",
        ]

        for tc in self.test_cases:
            test_name = tc.name.replace(" ", "_").lower()
            lines.append(f"def test_{test_name}():")
            if tc.description:
                lines.append(f'    """{tc.description}"""')

            # Generate assertion
            args = ", ".join(f"{k}={v!r}" for k, v in tc.inputs.items())
            if tc.expected is not None:
                lines.append(f"    result = {self.function_name}({args})")
                lines.append(f"    assert result == {tc.expected!r}")
            else:
                lines.append("    # No expected value provided")
                lines.append(f"    result = {self.function_name}({args})")
                lines.append("    assert result is not None  # Basic assertion")
            lines.append("")

        return "\n".join(lines)


def generate_tests(
    function_signature: str,
    function_name: str | None = None,
    num_tests: int = 5,
    include_edge_cases: bool = True,
) -> TestSuite:
    """Generate test cases from a function signature.

    Parses the function signature and generates test cases
    with representative inputs based on parameter types.

    Args:
        function_signature: Function signature string
        function_name: Override function name (optional)
        num_tests: Number of tests to generate
        include_edge_cases: Include edge case tests

    Returns:
        TestSuite with generated test cases

    Example:
        tests = generate_tests("def add(a: int, b: int) -> int")
        print(tests.to_pytest())
    """
    # Parse function signature
    parsed = _parse_signature(function_signature)
    fn_name = function_name or parsed["name"]
    params = parsed["params"]

    test_cases: list[TestCase] = []

    # Generate representative tests
    for i in range(num_tests):
        inputs = {}
        for param_name, param_type in params.items():
            inputs[param_name] = _generate_value(param_type, i)

        test_cases.append(
            TestCase(
                name=f"{fn_name}_test_{i + 1}",
                inputs=inputs,
                description=f"Test case {i + 1} for {fn_name}",
            )
        )

    # Add edge cases
    if include_edge_cases:
        edge_cases = _generate_edge_cases(params)
        for i, edge in enumerate(edge_cases):
            test_cases.append(
                TestCase(
                    name=f"{fn_name}_edge_{i + 1}",
                    inputs=edge,
                    description=f"Edge case {i + 1}",
                    is_edge_case=True,
                )
            )

    return TestSuite(
        name=f"TestSuite_{fn_name}",
        test_cases=test_cases,
        function_name=fn_name,
    )


def generate_property_tests(
    function_signature: str,
    properties: list[str] | None = None,
) -> str:
    """Generate property-based tests using Hypothesis.

    Creates Hypothesis-style property tests that verify
    properties hold for all inputs.

    Args:
        function_signature: Function signature string
        properties: List of properties to test (optional)

    Returns:
        Pytest code with Hypothesis decorators

    Example:
        code = generate_property_tests(
            "def add(a: int, b: int) -> int",
            properties=["result >= a", "result >= b"]
        )
    """
    parsed = _parse_signature(function_signature)
    fn_name = parsed["name"]
    params = parsed["params"]

    lines = [
        "import pytest",
        "from hypothesis import given, strategies as st",
        "",
        f"# Property-based tests for {fn_name}",
        "",
    ]

    # Build hypothesis strategies
    strategies = []
    for param_name, param_type in params.items():
        strategy = _type_to_hypothesis_strategy(param_type)
        strategies.append(f"{param_name}={strategy}")

    strategy_str = ", ".join(strategies)

    # Generate property test
    lines.append(f"@given({strategy_str})")
    args = ", ".join(params.keys())
    lines.append(f"def test_{fn_name}_properties({args}):")
    lines.append(f"    result = {fn_name}({args})")

    # Add property assertions
    if properties:
        for prop in properties:
            lines.append(f"    assert {prop}")
    else:
        lines.append("    # Add property assertions here")
        lines.append("    assert result is not None")

    lines.append("")

    return "\n".join(lines)


def _parse_signature(signature: str) -> dict[str, Any]:
    """Parse a function signature string."""
    # Extract function name
    name_match = re.search(r"def\s+(\w+)", signature)
    fn_name = name_match.group(1) if name_match else "unknown"

    # Extract parameters
    params_match = re.search(r"\(([^)]*)\)", signature)
    params: dict[str, str] = {}

    if params_match:
        params_str = params_match.group(1)
        for param in params_str.split(","):
            param = param.strip()
            if ":" in param:
                name, type_hint = param.split(":", 1)
                params[name.strip()] = type_hint.strip()
            elif param:
                params[param] = "Any"

    return {"name": fn_name, "params": params}


def _generate_value(type_hint: str, seed: int) -> Any:
    """Generate a test value for a type hint."""
    type_hint = type_hint.strip()

    if type_hint in ("int", "integer"):
        return [0, 1, -1, 42, 100][seed % 5]
    elif type_hint in ("float", "double"):
        return [0.0, 1.0, -1.0, 3.14, 0.001][seed % 5]
    elif type_hint in ("str", "string"):
        return ["", "hello", "test", "abc123", "special!@#"][seed % 5]
    elif type_hint in ("bool", "boolean"):
        return seed % 2 == 0
    elif type_hint.startswith("list[Any]"):
        return [[], [1], [1, 2], [1, 2, 3], list(range(10))][seed % 5]
    elif type_hint.startswith("dict[str, Any]"):
        return [{}, {"a": 1}, {"a": 1, "b": 2}][seed % 3]
    elif type_hint == "None":
        return None
    else:
        return f"<{type_hint}>"


def _generate_edge_cases(params: dict[str, str]) -> list[dict[str, Any]]:
    """Generate edge case inputs."""
    edge_cases = []

    # Boundary values per type
    boundaries = {
        "int": [0, -1, 1, 2**31 - 1, -(2**31)],
        "float": [0.0, -0.0, float("inf"), float("-inf"), float("nan")],
        "str": ["", " ", "\n", "\t", "a" * 1000],
        "bool": [True, False],
        "list[Any]": [[], [None], list(range(1000))],
    }

    # Generate edge cases for each parameter
    for param_name, param_type in params.items():
        type_key = param_type.strip().lower()
        if type_key in boundaries:
            for boundary_value in boundaries[type_key][:2]:  # type: ignore[index]
                inputs = {p: _generate_value(t, 0) for p, t in params.items()}
                inputs[param_name] = boundary_value
                edge_cases.append(inputs)

    return edge_cases[:5]  # Limit edge cases


def _type_to_hypothesis_strategy(type_hint: str) -> str:
    """Convert type hint to Hypothesis strategy."""
    type_hint = type_hint.strip().lower()

    strategies = {
        "int": "st.integers()",
        "float": "st.floats(allow_nan=False)",
        "str": "st.text(max_size=100)",
        "bool": "st.booleans()",
        "list[Any]": "st.lists(st.integers())",
        "dict[str, Any]": "st.dictionaries(st.text(), st.integers())",
    }

    return strategies.get(type_hint, "st.none()")


__all__ = [
    "TestCase",
    "TestSuite",
    "generate_property_tests",
    "generate_tests",
]
