// DO NOT EDIT - This file is auto-generated by generate_design_tokens.py
// Generated: 2026-01-05T11:46:27.533782
// Version: 1.0.0

#![allow(dead_code)]

//! Kagami Design System Tokens
//!
//! Single source of truth for LED ring colors and animations.

/// RGB color representation
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Color {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

impl Color {
    pub const fn new(r: u8, g: u8, b: u8) -> Self {
        Self { r, g, b }
    }

    pub fn to_rgb_tuple(&self) -> (u8, u8, u8) {
        (self.r, self.g, self.b)
    }

    pub fn to_hex(&self) -> String {
        format!("#{:02X}{:02X}{:02X}", self.r, self.g, self.b)
    }
}

pub mod colors {
    use super::Color;

    /// Colony colors (Octonion basis e1-e7)
    /// Synchronized with packages/kagami-design/design-tokens.json
    pub mod colony {
        use super::Color;
        /// Spark - Ideation (e1) - Red-Orange #FF6B35
        pub const SPARK: Color = Color::new(255, 107, 53);
        /// Forge - Implementation (e2) - Orange #FF9500
        pub const FORGE: Color = Color::new(255, 149, 0);
        /// Flow - Adaptation (e3) - Cyan #5AC8FA
        pub const FLOW: Color = Color::new(90, 200, 250);
        /// Nexus - Integration (e4) - Purple #AF52DE
        pub const NEXUS: Color = Color::new(175, 82, 222);
        /// Beacon - Planning (e5) - Yellow #FFD60A
        pub const BEACON: Color = Color::new(255, 214, 10);
        /// Grove - Research (e6) - Green #32D74B
        pub const GROVE: Color = Color::new(50, 215, 75);
        /// Crystal - Verification (e7) - Light Blue #64D2FF
        pub const CRYSTAL: Color = Color::new(100, 210, 255);
    }

    pub mod status {
        use super::Color;
        /// Success green
        pub const SUCCESS: Color = Color::new(0x00, 0xff, 0x88);
        /// Error red
        pub const ERROR: Color = Color::new(0xff, 0x44, 0x44);
        /// Warning yellow
        pub const WARNING: Color = Color::new(0xff, 0xd7, 0x00);
    }

    pub mod void {
        use super::Color;
        /// Primary background
        pub const VOID: Color = Color::new(0x07, 0x06, 0x0B);
        /// Light void
        pub const LIGHT: Color = Color::new(0x1a, 0x18, 0x20);
        /// Carbon
        pub const CARBON: Color = Color::new(0x25, 0x23, 0x30);
    }
}

pub mod motion {
    /// Animation durations in milliseconds
    pub mod duration {
        pub const INSTANT: u32 = 89;
        pub const FAST: u32 = 144;
        pub const NORMAL: u32 = 233;
        pub const SLOW: u32 = 377;
    }

    /// Easing function parameters (x1, y1, x2, y2)
    pub mod easing {
        pub const EASE_OUT: (f32, f32, f32, f32) = (0.0, 0.0, 0.2, 1.0);
        pub const EASE_IN_OUT: (f32, f32, f32, f32) = (0.4, 0.0, 0.2, 1.0);
    }
}

pub mod spacing {
    /// Base spacing unit
    pub const BASE: u32 = 8;
    /// Small spacing
    pub const SMALL: u32 = 4;
    /// Medium spacing
    pub const MEDIUM: u32 = 16;
    /// Large spacing
    pub const LARGE: u32 = 24;
}

pub mod radius {
    /// Small radius
    pub const SMALL: u32 = 4;
    /// Medium radius
    pub const MEDIUM: u32 = 8;
    /// Large radius
    pub const LARGE: u32 = 16;
}

/// LED Ring color presets for common states
pub mod led_presets {
    use super::colors;
    use super::Color;

    /// Listening state - soft flow blue-green
    pub const LISTENING: Color = colors::colony::FLOW;

    /// Processing state - warm spark orange
    pub const PROCESSING: Color = colors::colony::SPARK;

    /// Success state - bright green
    pub const SUCCESS: Color = colors::status::SUCCESS;

    /// Error state - red
    pub const ERROR: Color = colors::status::ERROR;

    /// Idle state - dim void
    pub const IDLE: Color = colors::void::LIGHT;

    /// Wake word detected - bright nexus purple
    pub const WAKE_WORD: Color = colors::colony::NEXUS;
}
