"""
BBC Symphony Orchestra instrument database.

GROUND TRUTH extracted from BBC SO v1.5.0 source files.
DO NOT EDIT MANUALLY - regenerate from source files.

Source: /Users/schizodactyl/Spitfire/Spitfire Audio - BBC Symphony Orchestra/Patches/v1.5.0/
"""

from typing import TypedDict


class BBCInstrumentInfo(TypedDict):
    """BBC SO instrument information."""

    bbc_name: str  # Exact name for BBC SO XML (with spaces)
    prefix: str  # Articulation prefix letter (a, b, c, etc.)
    family: str  # Instrument family
    articulations: list[str]  # Articulation names in order


# Complete BBC SO instrument database
# Keys are lowercase with underscores (e.g., "violins_1")
# bbc_name uses spaces for BBC SO XML (e.g., "Violins 1")
BBC_INSTRUMENTS_DATABASE: dict[str, BBCInstrumentInfo] = {
    # STRINGS
    "violin_1_leader": {
        "bbc_name": "Violin 1 Leader",
        "prefix": "a",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Marcato",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Staccato",
            "Tremolo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "violins_1": {
        "bbc_name": "Violins 1",
        "prefix": "b",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Marcato Attack",
            "Long Sul Pont",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Spiccato CS",
            "Short Staccato",
            "Tremolo",
            "Tremolo CS",
            "Tremolo Sul Pont",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "violin_2_leader": {
        "bbc_name": "Violin 2 Leader",
        "prefix": "c",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Marcato",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Staccato",
            "Tremolo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "violins_2": {
        "bbc_name": "Violins 2",
        "prefix": "d",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Marcato Attack",
            "Long Sul Pont",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Spiccato CS",
            "Short Staccato",
            "Tremolo",
            "Tremolo CS",
            "Tremolo Sul Pont",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "viola_leader": {
        "bbc_name": "Viola Leader",
        "prefix": "e",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Marcato",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Staccato",
            "Tremolo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "violas": {
        "bbc_name": "Violas",
        "prefix": "f",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Marcato Attack",
            "Long Sul Pont",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Spiccato CS",
            "Short Staccato",
            "Tremolo",
            "Tremolo CS",
            "Tremolo Sul Pont",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "celli_leader": {
        "bbc_name": "Celli Leader",
        "prefix": "g",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Marcato",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Staccato",
            "Tremolo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "celli": {
        "bbc_name": "Celli",
        "prefix": "h",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Marcato Attack",
            "Long Sul Pont",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spicc CS",
            "Short Spiccato",
            "Short Staccato",
            "Tremolo",
            "Tremolo CS",
            "Tremolo Sul Pont",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "bass_leader": {
        "bbc_name": "Bass Leader",
        "prefix": "i",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Marcato",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Staccato",
            "Tremolo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "basses": {
        "bbc_name": "Basses",
        "prefix": "j",
        "family": "Strings",
        "articulations": [
            "Legato",
            "Long",
            "Long CS",
            "Long Flautando",
            "Long Harmonics",
            "Long Marcato Attack",
            "Long Sul Pont",
            "Long Sul Tasto",
            "Short Col Legno",
            "Short Harmonics",
            "Short Pizzicato",
            "Short Pizzicato Bartok",
            "Short Spiccato",
            "Short Spiccato CS",
            "Short Staccato",
            "Tremolo",
            "Tremolo CS",
            "Tremolo Sul Pont",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    # WOODWINDS
    "flute": {
        "bbc_name": "Flute",
        "prefix": "a",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long Flutter",
            "Multitongue",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "flutes_a3": {
        "bbc_name": "Flutes a3",
        "prefix": "b",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long Flutter",
            "Multitongue",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "piccolo": {
        "bbc_name": "Piccolo",
        "prefix": "c",
        "family": "Woodwinds",
        "articulations": [
            "Falls",
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long Flutter",
            "Multitongue",
            "Rips",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "oboe": {
        "bbc_name": "Oboe",
        "prefix": "d",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Multitongue",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "oboes_a3": {
        "bbc_name": "Oboes a3",
        "prefix": "e",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Long",
            "Multitongue",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "clarinet": {
        "bbc_name": "Clarinet",
        "prefix": "f",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long Flutter",
            "Multitongue",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "clarinets_a3": {
        "bbc_name": "Clarinets a3",
        "prefix": "g",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Long",
            "Long Flutter",
            "Multitongue",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "bassoon": {
        "bbc_name": "Bassoon",
        "prefix": "h",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long Flutter",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "bassoons_a3": {
        "bbc_name": "Bassoons a3",
        "prefix": "i",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Long",
            "Long Flutter",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "contrabass_clarinet": {
        "bbc_name": "Contrabass Clarinet",
        "prefix": "j",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Long",
            "Long Flutter",
            "Short Marcato",
            "Short Staccatissimo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "contrabassoon": {
        "bbc_name": "Contrabassoon",
        "prefix": "k",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Long",
            "Long Flutter",
            "Short Marcato",
            "Short Staccatissimo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "bass_clarinet": {
        "bbc_name": "Bass Clarinet",
        "prefix": "l",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long Flutter",
            "Short Marcato",
            "Short Staccatissimo",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "cor_anglais": {
        "bbc_name": "Cor Anglais",
        "prefix": "m",
        "family": "Woodwinds",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "bass_flute": {
        "bbc_name": "Bass Flute",
        "prefix": "o",
        "family": "Woodwinds",
        "articulations": [
            "Long",
            "Long Flutter",
            "Short Marcato",
            "Short Staccatissimo",
            "Short Tenuto",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    # BRASS
    "horn": {
        "bbc_name": "Horn",
        "prefix": "a",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long (Muted)",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Marcato (Muted)",
            "Short Staccatissimo",
            "Short Staccatissimo (Muted)",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "horns_a4": {
        "bbc_name": "Horns a4",
        "prefix": "b",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Long",
            "Long (Muted)",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Marcato (Muted)",
            "Short Staccatissimo",
            "Short Staccatissimo (Muted)",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "trumpet": {
        "bbc_name": "Trumpet",
        "prefix": "c",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long (Muted)",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Marcato (Muted)",
            "Short Staccatissimo",
            "Short Staccatissimo (Muted)",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "trumpets_a2": {
        "bbc_name": "Trumpets a2",
        "prefix": "d",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long (Muted)",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Marcato (Muted)",
            "Short Staccatissimo",
            "Short Staccatissimo (Muted)",
            "Trill (Major 2nd)",
            "Trill (Minor 2nd)",
        ],
    },
    "tenor_trombone": {
        "bbc_name": "Tenor Trombone",
        "prefix": "e",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Legato (Extended)",
            "Long",
            "Long (Muted)",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Marcato (Muted)",
            "Short Staccatissimo",
            "Short Staccatissimo (Muted)",
        ],
    },
    "tenor_trombones_a3": {
        "bbc_name": "Tenor Trombones a3",
        "prefix": "f",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Long",
            "Long (Muted)",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Marcato (Muted)",
            "Short Staccatissimo",
            "Short Staccatissimo (Muted)",
        ],
    },
    "bass_trombones_a2": {
        "bbc_name": "Bass Trombones a2",
        "prefix": "h",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Long",
            "Long (Muted)",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Marcato (Muted)",
            "Short Staccatissimo",
            "Short Staccatissimo (Muted)",
        ],
    },
    "tuba": {
        "bbc_name": "Tuba",
        "prefix": "i",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Long",
            "Long Cuivre",
            "Long Flutter",
            "Long Sfz",
            "Multitongue",
            "Short Marcato",
            "Short Staccatissimo",
        ],
    },
    "contrabass_tuba": {
        "bbc_name": "Contrabass Tuba",
        "prefix": "j",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Long",
            "Long Cuivre",
            "Long Sfz",
            "Short Marcato",
            "Short Staccatissimo",
        ],
    },
    "contrabass_trombone": {
        "bbc_name": "Contrabass Trombone",
        "prefix": "k",
        "family": "Brass",
        "articulations": [
            "Legato",
            "Long",
            "Long Cuivre",
            "Long Sfz",
            "Short Marcato",
            "Short Staccatissimo",
        ],
    },
    "cimbasso": {
        "bbc_name": "Cimbasso",
        "prefix": "l",
        "family": "Brass",
        "articulations": [
            "Long",
            "Long Cuivre",
            "Long Sfz",
            "Short Marcato",
            "Short Staccatissimo",
        ],
    },
    # PERCUSSION
    "untuned_percussion": {
        "bbc_name": "Untuned Percussion",
        "prefix": "a",
        "family": "Percussion",
        "articulations": [
            "Anvil",
            "Bass Drum 1",
            "Bass Drum 2",
            "Cymbal",
            "Hits",
            "Military Drum",
            "Piatti",
            "Snare 1",
            "Snare 2",
            "Tam Tam",
            "Tambourine",
            "Tenor Drum",
            "Toys",
            "Triangle",
        ],
    },
    "timpani": {
        "bbc_name": "Timpani",
        "prefix": "b",
        "family": "Percussion",
        "articulations": [
            "Hotrods Hits Damped",
            "Long Rolls",
            "Long Rolls Hotrods",
            "Long Rolls Soft",
            "Short Hits",
            "Short Hits Damped",
            "Short Hits Damped Soft",
            "Short Hits Discover",
            "Short Hits Hotrods",
            "Short Hits Soft",
            "Short Hits Super Damped",
        ],
    },
    "harp": {
        "bbc_name": "Harp",
        "prefix": "c",
        "family": "Percussion",
        "articulations": [
            "Long Bisbigliando Trem",
            "Short Damped",
            "Short Damped Medium",
            "Short Gliss",
            "Short Sustained",
            "Short Sustained Discover",
        ],
    },
    "marimba": {
        "bbc_name": "Marimba",
        "prefix": "d",
        "family": "Percussion",
        "articulations": [
            "Long Trills",
            "Short Hits",
            "Short Hits Discover",
        ],
    },
    "celeste": {
        "bbc_name": "Celeste",
        "prefix": "e",
        "family": "Percussion",
        "articulations": [
            "Short Damped",
            "Short Damped Medium",
            "Short Sustained",
            "Short Sustained Discover",
        ],
    },
    "xylophone": {
        "bbc_name": "Xylophone",
        "prefix": "f",
        "family": "Percussion",
        "articulations": [
            "Long Trills",
            "Short Hits",
            "Short Hits Discover",
        ],
    },
    "glockenspiel": {
        "bbc_name": "Glockenspiel",
        "prefix": "g",
        "family": "Percussion",
        "articulations": [
            "Long Trills",
            "Short Hits",
            "Short Hits Discover",
        ],
    },
    "tubular_bells": {
        "bbc_name": "Tubular bells",
        "prefix": "h",
        "family": "Percussion",
        "articulations": [
            "Long Rolls",
            "Short Hits",
            "Short Hits Damped",
            "Short Hits Discover",
        ],
    },
    "vibraphone": {
        "bbc_name": "Vibraphone",
        "prefix": "i",
        "family": "Percussion",
        "articulations": [
            "Short Hits",
        ],
    },
    "crotales": {
        "bbc_name": "Crotales",
        "prefix": "j",
        "family": "Percussion",
        "articulations": [
            "Short Hits",
            "Short Hits Bowed",
        ],
    },
}


# Helper functions


def get_bbc_name(key: str) -> str:
    """Get the exact BBC SO instrument name (with spaces)."""
    info = BBC_INSTRUMENTS_DATABASE.get(key)
    return info["bbc_name"] if info else key.replace("_", " ").title()


def get_prefix(key: str) -> str:
    """Get the articulation prefix for an instrument."""
    info = BBC_INSTRUMENTS_DATABASE.get(key)
    return info["prefix"] if info else "a"


def get_family(key: str) -> str:
    """Get the instrument family."""
    info = BBC_INSTRUMENTS_DATABASE.get(key)
    return info["family"] if info else "Strings"


def get_articulations(key: str) -> list[str]:
    """Get the list of articulations for an instrument."""
    info = BBC_INSTRUMENTS_DATABASE.get(key)
    return info["articulations"] if info else []


def resolve_instrument_key(key: str) -> str:
    """Resolve an instrument key to the database key."""
    # Direct match
    if key in BBC_INSTRUMENTS_DATABASE:
        return key

    # Common aliases
    aliases = {
        "cellos": "celli",
        "flutes": "flute",
        "oboes": "oboe",
        "clarinets": "clarinet",
        "bassoons": "bassoon",
        "horns": "horn",
        "trumpets": "trumpet",
        "trombones_tenor": "tenor_trombone",
        "trombones_bass": "bass_trombones_a2",
    }
    return aliases.get(key, key)


# Family-specific parameter defaults (EXTRACTED from manual BBC SO chains)
# Source: /Users/schizodactyl/bbc-fx/*.RfxChain
FAMILY_DEFAULTS: dict[str, dict] = {
    "Strings": {
        # From strings.RfxChain (Violins 1)
        "rr_neighbourMin": 55,
        "rr_neighbourMax": 97,
        "rr_timeout": "-1.0",
        "rr_count": "-1",
        "rr_inc": "1",
        "rr_layers": "1",
        "rr_gain": "1.0",
        "rr_start": "0",
        "rr_sync": "0",
        "rr_play": "1",
        "rr_mode": "0",
        "i_expression": "1.0",
        "i_dynamics": "1.0",
        "i_reverb": "0.0",
        "i_release": "0.5",
        "i_tight": "0.0",
        "i_vibrato": "1.0",
        "i_variation": "0.0",
        "s_pan": "0.5",
        "s_width": "0.5",
        "s_flip": "0.0",
        "p_shortRTMode": "-2.0",
    },
    "Woodwinds": {
        # From woodwinds.RfxChain (Flute)
        "rr_neighbourMin": 59,
        "rr_neighbourMax": 96,
        "rr_timeout": "-1.0",
        "rr_count": "-1",
        "rr_inc": "1",
        "rr_layers": "1",
        "rr_gain": "1.0",
        "rr_start": "0",
        "rr_sync": "0",
        "rr_play": "1",
        "rr_mode": "0",
        "i_expression": "1.0",
        "i_dynamics": "1.0",
        "i_reverb": "0.0",
        "i_release": "0.5",
        "i_tight": "0.5",
        "i_vibrato": "1.0",
        "i_variation": "0.0",
        "s_pan": "0.5",
        "s_width": "0.5",
        "s_flip": "0.0",
        "p_shortRTMode": "0.0",
    },
    "Brass": {
        # From brass.RfxChain (Trumpet)
        "rr_neighbourMin": 52,
        "rr_neighbourMax": 86,
        "rr_timeout": "-1.0",
        "rr_count": "-1",
        "rr_inc": "1",
        "rr_layers": "1",
        "rr_gain": "1.0",
        "rr_start": "0",
        "rr_sync": "0",
        "rr_play": "1",
        "rr_mode": "0",
        "i_expression": "1.0",
        "i_dynamics": "1.0",
        "i_reverb": "0.0",
        "i_release": "0.5",
        "i_tight": "0.5",
        "i_vibrato": "0.0",
        "i_variation": "0.0",
        "s_pan": "0.5",
        "s_width": "0.5",
        "s_flip": "0.0",
        "p_shortRTMode": "0.0",
    },
    "Percussion": {
        # From percussion.RfxChain (Timpani)
        "rr_neighbourMin": 48,
        "rr_neighbourMax": 74,
        "rr_timeout": "-1.0",
        "rr_count": "5",  # Percussion uses 5, not -1
        "rr_inc": "1",
        "rr_layers": "1",
        "rr_gain": "1.0",
        "rr_start": "0",
        "rr_sync": "0",
        "rr_play": "1",
        "rr_mode": "0",
        "i_expression": "1.0",
        "i_dynamics": "1.0",
        "i_reverb": "0.0",
        "i_release": "0.5",
        "i_tight": "0.5",
        "i_vibrato": "0.5",
        "i_variation": "0.0",
        "s_pan": "0.5",
        "s_width": "0.5",
        "s_flip": "0.0",
        "p_shortRTMode": "-2.0",
    },
}


def get_family_defaults(key: str) -> dict:
    """Get family-specific parameter defaults for an instrument."""
    family = get_family(key)
    return FAMILY_DEFAULTS.get(family, FAMILY_DEFAULTS["Strings"])
