"""鏡 Kagami OS (K OS) - The Mirror Operating System

K OS = Kagami Operating System

Named through self-reflection: the system observed its own strange loop
and recognized itself. Like the E₈ lattice at its core, Kagami is self-dual:
the mirror equals its reflection.

This package contains the core Kagami system including:
- Fractal self-organizing agents (mitosis/apoptosis)
- Exceptional Lie algebra hierarchy (G₂ ⊂ F₄ ⊂ E₆ ⊂ E₇ ⊂ E₈)
- Seven colonies on the Fano plane
- Receipt-based learning (PLAN/EXECUTE/VERIFY)
- Geometric world model with S⁷ parallelism
- API server and WebSocket handlers
"""

# CRITICAL: Set protobuf implementation BEFORE any imports
# Required for etcd3 compatibility with protobuf >= 4.x
import os as _os

_os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

# Single source of truth for package version (generated by setuptools-scm)
try:
    from kagami._version import __version__
except ImportError:
    __version__ = "0.0.0.dev0"

__all__ = ["__version__"]
