// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(kagami_mesh_sdkFFI)
import kagami_mesh_sdkFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_kagami_mesh_sdk_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_kagami_mesh_sdk_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A connection state tracker for UniFFI.
 */
public protocol MeshConnectionProtocol : AnyObject {

    /**
     * Get the current backoff in milliseconds.
     */
    func backoffMs()  -> UInt64

    /**
     * Get the failure count.
     */
    func failureCount()  -> UInt32

    /**
     * Check if connected.
     */
    func isConnected()  -> Bool

    /**
     * Signal a connection attempt.
     */
    func onConnect() throws  -> String

    /**
     * Signal a successful connection.
     */
    func onConnected() throws  -> String

    /**
     * Signal disconnection.
     */
    func onDisconnect(reason: String) throws  -> String

    /**
     * Signal a connection failure.
     */
    func onFailure(reason: String) throws  -> String

    /**
     * Reset the state machine.
     */
    func reset()

    /**
     * Check if circuit breaker recovery is due.
     */
    func shouldAttemptRecovery()  -> Bool

    /**
     * Get the current state as a string.
     */
    func state()  -> String

}

/**
 * A connection state tracker for UniFFI.
 */
open class MeshConnection:
    MeshConnectionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_kagami_mesh_sdk_fn_clone_meshconnection(self.pointer, $0) }
    }
    /**
     * Create a new connection tracker with default config.
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_constructor_meshconnection_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_kagami_mesh_sdk_fn_free_meshconnection(pointer, $0) }
    }


    /**
     * Create with custom failure threshold.
     */
public static func withFailureThreshold(threshold: UInt32) -> MeshConnection {
    return try!  FfiConverterTypeMeshConnection.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_constructor_meshconnection_with_failure_threshold(
        FfiConverterUInt32.lower(threshold),$0
    )
})
}



    /**
     * Get the current backoff in milliseconds.
     */
open func backoffMs() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_backoff_ms(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Get the failure count.
     */
open func failureCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_failure_count(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Check if connected.
     */
open func isConnected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_is_connected(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Signal a connection attempt.
     */
open func onConnect()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_on_connect(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Signal a successful connection.
     */
open func onConnected()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_on_connected(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Signal disconnection.
     */
open func onDisconnect(reason: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_on_disconnect(self.uniffiClonePointer(),
        FfiConverterString.lower(reason),$0
    )
})
}

    /**
     * Signal a connection failure.
     */
open func onFailure(reason: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_on_failure(self.uniffiClonePointer(),
        FfiConverterString.lower(reason),$0
    )
})
}

    /**
     * Reset the state machine.
     */
open func reset() {try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_reset(self.uniffiClonePointer(),$0
    )
}
}

    /**
     * Check if circuit breaker recovery is due.
     */
open func shouldAttemptRecovery() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_should_attempt_recovery(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Get the current state as a string.
     */
open func state() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshconnection_state(self.uniffiClonePointer(),$0
    )
})
}


}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeshConnection: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MeshConnection

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MeshConnection {
        return MeshConnection(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MeshConnection) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MeshConnection {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MeshConnection, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeshConnection_lift(_ pointer: UnsafeMutableRawPointer) throws -> MeshConnection {
    return try FfiConverterTypeMeshConnection.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeshConnection_lower(_ value: MeshConnection) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMeshConnection.lower(value)
}




/**
 * A mesh network identity for UniFFI.
 */
public protocol MeshIdentityProtocol : AnyObject {

    /**
     * Get the peer ID (hex-encoded public key).
     */
    func peerId()  -> String

    /**
     * Get the public key as hex.
     */
    func publicKeyHex()  -> String

    /**
     * Sign a message.
     */
    func sign(message: Data)  -> String

    /**
     * Export as base64-encoded secret key.
     */
    func toBase64()  -> String

    /**
     * Verify a signature.
     */
    func verify(message: Data, signatureHex: String) throws  -> Bool

}

/**
 * A mesh network identity for UniFFI.
 */
open class MeshIdentity:
    MeshIdentityProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_kagami_mesh_sdk_fn_clone_meshidentity(self.pointer, $0) }
    }
    /**
     * Create a new random identity.
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_constructor_meshidentity_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_kagami_mesh_sdk_fn_free_meshidentity(pointer, $0) }
    }


    /**
     * Create an identity from a base64-encoded secret key.
     */
public static func fromBase64(encoded: String)throws  -> MeshIdentity {
    return try  FfiConverterTypeMeshIdentity.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_constructor_meshidentity_from_base64(
        FfiConverterString.lower(encoded),$0
    )
})
}



    /**
     * Get the peer ID (hex-encoded public key).
     */
open func peerId() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshidentity_peer_id(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Get the public key as hex.
     */
open func publicKeyHex() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshidentity_public_key_hex(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Sign a message.
     */
open func sign(message: Data) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshidentity_sign(self.uniffiClonePointer(),
        FfiConverterData.lower(message),$0
    )
})
}

    /**
     * Export as base64-encoded secret key.
     */
open func toBase64() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_method_meshidentity_to_base64(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Verify a signature.
     */
open func verify(message: Data, signatureHex: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_method_meshidentity_verify(self.uniffiClonePointer(),
        FfiConverterData.lower(message),
        FfiConverterString.lower(signatureHex),$0
    )
})
}


}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeshIdentity: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MeshIdentity

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MeshIdentity {
        return MeshIdentity(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MeshIdentity) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MeshIdentity {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MeshIdentity, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeshIdentity_lift(_ pointer: UnsafeMutableRawPointer) throws -> MeshIdentity {
    return try FfiConverterTypeMeshIdentity.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeshIdentity_lower(_ value: MeshIdentity) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMeshIdentity.lower(value)
}


/**
 * X25519 key pair result for UniFFI.
 */
public struct X25519KeyPair {
    public var secretKeyHex: String
    public var publicKeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretKeyHex: String, publicKeyHex: String) {
        self.secretKeyHex = secretKeyHex
        self.publicKeyHex = publicKeyHex
    }
}



extension X25519KeyPair: Equatable, Hashable {
    public static func ==(lhs: X25519KeyPair, rhs: X25519KeyPair) -> Bool {
        if lhs.secretKeyHex != rhs.secretKeyHex {
            return false
        }
        if lhs.publicKeyHex != rhs.publicKeyHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(secretKeyHex)
        hasher.combine(publicKeyHex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeX25519KeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> X25519KeyPair {
        return
            try X25519KeyPair(
                secretKeyHex: FfiConverterString.read(from: &buf),
                publicKeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: X25519KeyPair, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secretKeyHex, into: &buf)
        FfiConverterString.write(value.publicKeyHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeX25519KeyPair_lift(_ buf: RustBuffer) throws -> X25519KeyPair {
    return try FfiConverterTypeX25519KeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeX25519KeyPair_lower(_ value: X25519KeyPair) -> RustBuffer {
    return FfiConverterTypeX25519KeyPair.lower(value)
}


/**
 * Error type for UniFFI exports.
 */
public enum MeshSdkError {



    case InvalidInput(message: String
    )
    case CryptoError(message: String
    )
    case ParseError(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeshSdkError: FfiConverterRustBuffer {
    typealias SwiftType = MeshSdkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MeshSdkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .CryptoError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .ParseError(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MeshSdkError, into buf: inout [UInt8]) {
        switch value {





        case let .InvalidInput(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)


        case let .CryptoError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)


        case let .ParseError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)

        }
    }
}


extension MeshSdkError: Equatable, Hashable {}

extension MeshSdkError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}
/**
 * Decrypt data with XChaCha20-Poly1305.
 */
public func decryptData(keyHex: String, ciphertextHex: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_decrypt_data(
        FfiConverterString.lower(keyHex),
        FfiConverterString.lower(ciphertextHex),$0
    )
})
}
/**
 * Encrypt data with XChaCha20-Poly1305.
 *
 * Returns the ciphertext as a hex-encoded string (includes nonce).
 */
public func encryptData(keyHex: String, plaintext: Data)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_encrypt_data(
        FfiConverterString.lower(keyHex),
        FfiConverterData.lower(plaintext),$0
    )
})
}
/**
 * Increment a G-Counter.
 */
public func gCounterIncrement(counterJson: String, nodeId: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_g_counter_increment(
        FfiConverterString.lower(counterJson),
        FfiConverterString.lower(nodeId),$0
    )
})
}
/**
 * Merge two G-Counters.
 */
public func gCounterMerge(counter1Json: String, counter2Json: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_g_counter_merge(
        FfiConverterString.lower(counter1Json),
        FfiConverterString.lower(counter2Json),$0
    )
})
}
/**
 * Create a new G-Counter.
 */
public func gCounterNew() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_func_g_counter_new($0
    )
})
}
/**
 * Get the value of a G-Counter.
 */
public func gCounterValue(counterJson: String)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_g_counter_value(
        FfiConverterString.lower(counterJson),$0
    )
})
}
/**
 * Generate a new random XChaCha20-Poly1305 encryption key.
 *
 * Returns the key as a hex-encoded string.
 */
public func generateCipherKey() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_func_generate_cipher_key($0
    )
})
}
/**
 * Generate a new random Ed25519 identity.
 *
 * Returns the identity as a base64-encoded secret key string.
 */
public func generateIdentity() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_func_generate_identity($0
    )
})
}
/**
 * Generate an X25519 key pair.
 *
 * Returns the secret and public keys as hex-encoded strings.
 */
public func generateX25519Keypair() -> X25519KeyPair {
    return try!  FfiConverterTypeX25519KeyPair.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_func_generate_x25519_keypair($0
    )
})
}
/**
 * Get the peer ID (hex-encoded public key) from a base64-encoded identity.
 */
public func getPeerId(identityBase64: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_get_peer_id(
        FfiConverterString.lower(identityBase64),$0
    )
})
}
/**
 * Sign a message with an identity.
 *
 * Returns the signature as a hex-encoded string.
 */
public func signMessage(identityBase64: String, message: Data)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_sign_message(
        FfiConverterString.lower(identityBase64),
        FfiConverterData.lower(message),$0
    )
})
}
/**
 * Compare two vector clocks.
 *
 * Returns: "before", "after", "concurrent", or "equal".
 */
public func vectorClockCompare(clock1Json: String, clock2Json: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_vector_clock_compare(
        FfiConverterString.lower(clock1Json),
        FfiConverterString.lower(clock2Json),$0
    )
})
}
/**
 * Increment a vector clock for a node.
 */
public func vectorClockIncrement(clockJson: String, nodeId: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_vector_clock_increment(
        FfiConverterString.lower(clockJson),
        FfiConverterString.lower(nodeId),$0
    )
})
}
/**
 * Merge two vector clocks.
 */
public func vectorClockMerge(clock1Json: String, clock2Json: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_vector_clock_merge(
        FfiConverterString.lower(clock1Json),
        FfiConverterString.lower(clock2Json),$0
    )
})
}
/**
 * Create a new vector clock for a node.
 */
public func vectorClockNew(nodeId: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_kagami_mesh_sdk_fn_func_vector_clock_new(
        FfiConverterString.lower(nodeId),$0
    )
})
}
/**
 * Verify a signature on a message.
 */
public func verifySignature(publicKeyHex: String, message: Data, signatureHex: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_verify_signature(
        FfiConverterString.lower(publicKeyHex),
        FfiConverterData.lower(message),
        FfiConverterString.lower(signatureHex),$0
    )
})
}
/**
 * Perform X25519 Diffie-Hellman key exchange.
 *
 * Returns the derived encryption key as a hex string.
 */
public func x25519DeriveKey(secretKeyHex: String, peerPublicKeyHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMeshSdkError.lift) {
    uniffi_kagami_mesh_sdk_fn_func_x25519_derive_key(
        FfiConverterString.lower(secretKeyHex),
        FfiConverterString.lower(peerPublicKeyHex),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_kagami_mesh_sdk_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_decrypt_data() != 15656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_encrypt_data() != 52) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_g_counter_increment() != 4054) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_g_counter_merge() != 1925) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_g_counter_new() != 59457) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_g_counter_value() != 3557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_generate_cipher_key() != 21645) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_generate_identity() != 43220) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_generate_x25519_keypair() != 11422) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_get_peer_id() != 27617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_sign_message() != 20052) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_vector_clock_compare() != 28342) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_vector_clock_increment() != 12274) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_vector_clock_merge() != 21686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_vector_clock_new() != 51623) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_verify_signature() != 13582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_func_x25519_derive_key() != 57870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_backoff_ms() != 9668) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_failure_count() != 57113) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_is_connected() != 7031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_on_connect() != 27143) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_on_connected() != 6598) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_on_disconnect() != 59163) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_on_failure() != 12763) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_reset() != 13353) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_should_attempt_recovery() != 23838) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshconnection_state() != 35971) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshidentity_peer_id() != 924) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshidentity_public_key_hex() != 46235) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshidentity_sign() != 59089) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshidentity_to_base64() != 8849) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_method_meshidentity_verify() != 19352) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_constructor_meshconnection_new() != 1571) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_constructor_meshconnection_with_failure_threshold() != 49259) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_constructor_meshidentity_from_base64() != 64979) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_kagami_mesh_sdk_checksum_constructor_meshidentity_new() != 26521) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
